# Request Codes
CALIBRATE_IMU = 0
ZERO_AXIS = 1
CALIBRATE_OFS = 2

# Return Codes
SUCCESS=0
FAIL = 1
FAIL_UNRECOGNISED_OP_CODE = 2
FAIL_DETECTED_NO_TOF_FORWARD = 3
FAIL_DETECTED_NO_OFS_FORWARD = 4
FAIL_TOF_DETECTED_NO_REASONABLE_RANGE = 5

# Service
CODE_TERMINATE = 0
CODE_CONTINUE = 1

# geo_location
GEO_BACKUP_PERIOD = 2.0
