# Define All Modes and Flags
# byte data type does not work in the python conversion stick to uint8
#etc...
uint8 CALIBRATE_IMU=0
uint8 ZERO_AXIS=1
uint8 CALIBRATE_OFS=2 
# Sets the Mode
uint8 code

# used for calibrating the OFS
float32 move_time
---
# Define return codes
uint8 SUCCESS=0
uint8 FAIL=1
uint8 FAIL_UNRECOGNISED_OP_CODE=2

# Returns diagnostic information about change of state.
uint8 result

---
# seconds until completion
uint32 seconds
